### ISSUE TITLE
Documents?

### ISSUE THREAD

**Issue by tiye** [intelie/immutable-js-patch#1]
I'm quite interested about this project, how about docs?

Related to https://github.com/intelie/immutable-js-diff/issues/2 and https://github.com/facebook/flux/issues/105

**Comment by brenoferreira** [comment]
Yes, we should have some documentation. I'll try to have some docs up soon.
Meanwhile, if you're interested, take a look at the test suite for both [immutable-js-diff](https://github.com/intelie/immutable-js-diff/tree/master/tests) and [immutable-js-patch](https://github.com/intelie/immutable-js-patch/tree/master/tests). There are many tests that cover quite a few cases, so you should have a better understanding of how to use it after that.
