### ISSUE TITLE
Cannot do complete replace of Immutable Object

### ISSUE THREAD

**Issue by steveccable** [intelie/immutable-js-patch#10]
Normally, I do diff (from immutable-diff) followed by a patch, and this works fine when the two objects are fairly similar.  However, when they are completely different objects, the diff produces a single replace with a path of "/" and patch fails to interpret this path, instead just returning the original Immutable.

It seems that a more reasonable approach would be to have a replace with no specified path result in an actual replacement of the Immutable object.

**Comment by pedroteixeira** [comment]
It makes sense. Thanks for reporting, Steve.  Feel free to provide a pull request, and I'd release a version with the improvement. Otherwise, I'll probably only have some time to look at it in middle January.
