### ISSUE TITLE
Unable to add new key:val to nested object

### ISSUE THREAD

**Issue by pirate** [intelie/immutable-js-patch#7]
``` javascript
myobject = new Map({a: {1: 1, 2: 2, 3: 3}})
patches = new List([new Map({op: 'add', path: '/a/4', value: 4})])
patch(myobject, patches).toJS()
>>Object {a: 4}

// expected: {a: {1: 1, 2: 2, 3: 3, 4: 4}}
```

Seems like a bug, there should definitely be a way to add a value to a sub-object without having to use replace.  That's the point of having a path after all right?

Thanks!  I'll work on a PR to fix it when I get some time after this weekend.

**Comment by brenoferreira** [comment]
This looks like a bug when the key of the Map is of type `number`.

**Comment by pedroteixeira** [comment]
@pirate have you tried `myobject = Immutable.fromJS({a: {1: 1, 2: 2, 3: 3}})`?  It seems you are creating a shallow Map with a nested native object.

**Comment by brenoferreira** [comment]
That's right @pedroteixeira Just tested it here and it works

```
> myobject = Immutable.fromJS({a: {1: 1, 2: 2, 3: 3}})
=> Map { a: Map { 1: 1, 2: 2, 3: 3 } }
> patches = new Immutable.List([new Immutable.Map({op: 'add', path: '/a/4', value: 4})])
=> List [ Map { op: "add", path: "/a/4", value: 4 } ]
> patch(myobject, patches).toJS()
=> { a:
   { '1': 1,
     '2': 2,
     '3': 3,
     '4': 4 } }
```

@pirate using `fromJS` gives the expected output, since the value of `a` will be a Immutable Map as well (instead of a JS Object)

**Comment by pirate** [comment]
Thanks! You're totally right, I don't know why I didn't realize the nested object wasn't an immutable Map. Works like a charm!
